### ISSUE TITLE
您好，插件出错了

### ISSUE THREAD

**Issue by gaoqingkong** [hsfzxjy/xxqg-addon#14]
大神您好！那个学习插件出了点小状况，回到积分页面故障依旧，一般得分不超过10分，有时无拖动页面动作，看完文章或视频后不能自动点击其他页面继续拿分.....如有打扰请见谅，最后衷心感谢您的辛苦付出，诚祝顺心如意！

**Comment by hsfzxjy** [comment]
@gaoqingkong 已修复
