### ISSUE TITLE
文章自动返回BUG

### ISSUE THREAD

**Issue by Mimiers** [hsfzxjy/xxqg-addon#15]
如果是阅读文章的话,只会停留在第一个文章的页面,得不到反馈也不会返回到积分详情检索积分信息重新进行下一文章的阅读,永远停留到第一个阅读文章,不会跳转到第二个文章或者积分详情.从而卡住后面的阅读文章和视频进程,永远停留在一开始的第一个阅读文章.
且阅读第一个文章时(如果是学习理论,就不会自动进行鼠标滚动,如果是头条文章这是正常并会自动进行阅读下一篇)

当文章积分获取完毕时,会进入到浏览视频页面,这个时候是正常的,可以自动进行.浏览视频页面时会获取到反馈自动检索积分继续学习.

**Comment by Mimiers** [comment]
新的网页版不再支持31 分，变为25分,包括：

每日登录 1 分
阅读文章 6 分
观看视频 6 分
阅读时长 6 分
视频时长 6分

**Comment by hsfzxjy** [comment]
@Mimiers 已修复
