### ISSUE TITLE
似乎从您发的油猴下载链接下载到的油猴已经损坏

### ISSUE THREAD

**Issue by HarsonLau** [hsfzxjy/xxqg-addon#2]

**Comment by hsfzxjy** [comment]
多谢反馈，应该是打包时有错误，预计在两天内修复。如果可以上 google 的话可以尝试从 chrome app 商店获取 TamperMonkey

**Comment by noway2014** [comment]
ok了吗？

**Comment by hsfzxjy** [comment]
可以通过如下方式解决：

下载以下文件 [TamperMonkey.zip](https://github.com/hsfzxjy/xxqg-addon/files/2941038/TamperMonkey.zip) ，解压。

前往 chrome://extensions，点击 Load Unpacked / 加载已解压的扩展程序，选择解压好的 4.8_0 文件夹。完成安装

**Comment by noway2014** [comment]
按照readme提示方法，到最后导入https://github.com/hsfzxjy/xxqg-addon/raw/master/build/xxqg.js。提示无法从该url加载剧本。
不知道为何？？

**Comment by hsfzxjy** [comment]
我觉得是和后面的中文连在一起了 这个是链接 https://github.com/hsfzxjy/xxqg-addon/raw/master/build/xxqg.js

**Comment by noway2014** [comment]
不是，是手动输入，都无法导入。你试过吗？

2019年3月8日 10:56，"Xie Jingyi" <notifications@github.com>写道：

**Comment by hsfzxjy** [comment]
我在Win7上试过，是成功的

**Comment by noway2014** [comment]
我再试试…谢谢
