### ISSUE TITLE
论如何加快学习速度

### ISSUE THREAD

**Issue by democrazyx** [hsfzxjy/xxqg-addon#5]
学习强国里的学习时间判定是由网页向服务器发送的pclog信息决定的，只取决于发送pclog的次数，与其发送时间间隔无关（我已经测试过了），然后可以通过脚本加快学习速度，网页加载快的话，只需要几分钟就可刷满30分。
具体可以查看[代码](https://github.com/Demcorazy/MyLearningRoad/blob/master/学习强国.js)，工作原理是把原网页用于发送pclog的laydate.js稍微修改一下，改变其定时器的频率，修改判断条件函数使document.hidden属性为false的时候也发送pclog，这样就不需要停留在页面了，因为需要使用原网页的其他对象，所以把代码作为script直接插入原网页。如果想要精简script，则需要破解pclog的产生流程，由于本人技术和时间有限暂时破解不了，希望能有大佬帮忙看一下。

**Comment by vocaliu** [comment]
> 学习强国里的学习时间判定是由网页向服务器发送的pclog信息决定的，只取决于发送pclog的次数，与其发送时间间隔无关（我已经测试过了），然后可以通过脚本加快学习速度，网页加载快的话，只需要几分钟就可刷满30分。
> 具体可以查看[代码](https://github.com/Demcorazy/MyLearningRoad/blob/master/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js)，工作原理是把原网页用于发送pclog的laydate.js稍微修改一下，改变其定时器的频率，修改判断条件函数使document.hidden属性为false的时候也发送pclog，这样就不需要停留在页面了，因为需要使用原网页的其他对象，所以把代码作为script直接插入原网页。如果想要精简script，则需要破解pclog的产生流程，由于本人技术和时间有限暂时破解不了，希望能有大佬帮忙看一下。

你看看这个
https://greasyfork.org/zh-CN/scripts/379910-xxqg-points/

**Comment by democrazyx** [comment]
> > 学习强国里的学习时间判定是由网页向服务器发送的pclog信息决定的，只取决于发送pclog的次数，与其发送时间间隔无关（我已经测试过了），然后可以通过脚本加快学习速度，网页加载快的话，只需要几分钟就可刷满30分。
> > 具体可以查看[代码](https://github.com/Demcorazy/MyLearningRoad/blob/master/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js)，工作原理是把原网页用于发送pclog的laydate.js稍微修改一下，改变其定时器的频率，修改判断条件函数使document.hidden属性为false的时候也发送pclog，这样就不需要停留在页面了，因为需要使用原网页的其他对象，所以把代码作为script直接插入原网页。如果想要精简script，则需要破解pclog的产生流程，由于本人技术和时间有限暂时破解不了，希望能有大佬帮忙看一下。
> 
> 你看看这个
> https://greasyfork.org/zh-CN/scripts/379910-xxqg-points/

这就是我上传的，如果能把这两个脚本合并起来就好了，每天只要几分钟就可以31积分

**Comment by vocaliu** [comment]
> > > 学习强国里的学习时间判定是由网页向服务器发送的pclog信息决定的，只取决于发送pclog的次数，与其发送时间间隔无关（我已经测试过了），然后可以通过脚本加快学习速度，网页加载快的话，只需要几分钟就可刷满30分。
> > > 具体可以查看[代码](https://github.com/Demcorazy/MyLearningRoad/blob/master/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js)，工作原理是把原网页用于发送pclog的laydate.js稍微修改一下，改变其定时器的频率，修改判断条件函数使document.hidden属性为false的时候也发送pclog，这样就不需要停留在页面了，因为需要使用原网页的其他对象，所以把代码作为script直接插入原网页。如果想要精简script，则需要破解pclog的产生流程，由于本人技术和时间有限暂时破解不了，希望能有大佬帮忙看一下。
> > 
> > 
> > 你看看这个
> > https://greasyfork.org/zh-CN/scripts/379910-xxqg-points/
> 
> 这就是我上传的，如果能把这两个脚本合并起来就好了，每天只要几分钟就可以31积分

哈哈哈尴尬了没注意作者。。。

**Comment by noway2014** [comment]
楼上你好，这个脚本这个能实现什么功能？我能试试吗？怎么用？

**Comment by democrazyx** [comment]
> 楼上你好，这个脚本这个能实现什么功能？我能试试吗？怎么用？

就是可以把网页最小化，然后服务器后台还会给你计入学习时间， 并且可以快速获得学习时长。把脚本放在油猴里就可以用了

**Comment by noway2014** [comment]
打开网页或者视频，然后最小化？问题是最小化至少多久才有效呢？打开网页后有一个提示加速正在启动，然后就没有下文了呀。

**Comment by hsfzxjy** [comment]
@noway2014 前两天改版了，刚修复了

**Comment by democrazyx** [comment]
> 打开网页或者视频，然后最小化？问题是最小化至少多久才有效呢？打开网页后有一个提示加速正在启动，然后就没有下文了呀。

刷积分的时候可以打开刷积分的页面看刷了多少，有时候会因为网络问题而没有加速效果，这种时候再打开另外的页面就行了。

**Comment by noway2014** [comment]
能否有一个提示，就是可以提示可以加速结束，请关闭本页面的意思。要不，不知道效果呢。而且多页面浏览器，怎么最小化页面？一般都是关闭页面标签吧

**Comment by hsfzxjy** [comment]
> 能否有一个提示，就是可以提示可以加速结束，请关闭本页面的意思。要不，不知道效果呢。而且多页面浏览器，怎么最小化页面？一般都是关闭页面标签吧

全部刷满时脚本自己就会停下来。多标签浏览器也可以整个窗口最小化。

**Comment by noway2014** [comment]
楼上的脚本很正常，我这里说的是一楼的那个加速脚本

**Comment by hahaha123-commits** [comment]
是一直要打开当前的标签页吗，切换标签页之后是不是不行了？

**Comment by democrazyx** [comment]
> 是一直要打开当前的标签页吗，切换标签页之后是不是不行了？

切换标签也可以，只要不直接×掉。今天改了一下，优化了体验

**Comment by noway2014** [comment]
@demcorazy
看到已经有计时窗口，但是建议继续优化成可以提示完成关闭页面。因为纯粹计时，也不知道是否应该关闭呢。

**Comment by hsfzxjy** [comment]
@vocaliu @hekaiyu @Demcorazy 已支持到当前版本
