### ISSUE TITLE
3-20日起似乎不能用了，页面上不再弹出刷分框，是页面改版了吗。

### ISSUE THREAD

**Issue by JazzeZhang** [hsfzxjy/xxqg-addon#6]
如题，尝试重启和重装油猴均无用

**Comment by sephiroth945** [comment]
我也不能用了

**Comment by MarsMeow** [comment]
大佬们有解决办法么？

**Comment by brynn7** [comment]
同样不能用，看样子是改版了，感觉还加了限制。

**Comment by jjboomcn** [comment]
昨天才发现这么好用的工具，哭了

**Comment by jiejie2004** [comment]
学习研究->学习理论。

**Comment by hsfzxjy** [comment]
已修复，是标题改了。
抱歉最近比较忙，不能及时跟进。

**Comment by MarsMeow** [comment]
能分享出来并更新就很感激了，怎么能要求您及时更新呢

**Comment by jjboomcn** [comment]
> 已修复，是标题改了。
> 抱歉最近比较忙，不能及时跟进。

惭愧惭愧，白嫖大佬的代码，真是十分感谢了

**Comment by JazzeZhang** [comment]
感谢大佬的支持，我本来还想只能抽空学习js入门到放弃呢，不会前端。。。这个油猴是直接每次读取url的内容么，不用手工更新就能直接用了
